---
- hosts: all
  user: ansible
  sudo: yes
  tasks:
    - name: dfdfnld
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - telnet
    - name: start the service
      service:
        name: start appache
        state: started
        enabled: yes

