---
- hosts: local
  user: jenkins
  become: yes
  become_method: sudo
  tasks:
  - name: 
    debug:
      msg: "hi dear "
  - name: touch a file
    file:
     name: fem.txt
     state: touch
     
