#!/bin/python
import time
start_time = time.localtime()
print("Timer start at %s" % time.strftime("%X",start_time))
# wait for user input
raw_input("please press Enter to continue....")
stop_time=time.localtime()
difference=time.mktime(stop_time)-time.mktime(start_time)
print("timer stopped at %s" % time.strftime("%X",stop_time))
print("total time: %s seconds" % difference)
