---
- hosts: local
  user: ansible
  become: yes
  become_method: sudo
  tasks:
  - name: verify application processes are not running
    shell: if ps -eaf | egrep 'apache|http'|grep -v grep > /dev/null;then echo 'process_running';else echo 'process_not_running';fi
    ignore_errors: true
    register: app_process_check
  - name: decission point to start
    fail: msg="app_process_check"
    #when: app_process_check.stdout == 'process_running'
